// frontend/src/layout/Lane.svelte
<script lang="ts">
  import { cn } from '$lib/utils/cn';
  import { clearDrag, setLaneDrag } from '$lib/state/dragState';
  import CollapsedLane from './CollapsedLane.svelte';
  import LaneDragHandle from './LaneDragHandle.svelte';

  interface Props {
    id: string;
    title: string;
    children?: import('svelte').Snippet;
    collapsed: boolean;
    onToggleCollapse: () => void;
    width: number;
    fill?: boolean;
    dragOverId?: string | null;
    onRename?: () => void;
    onDelete?: () => void;
  }

  let { id, title, children, collapsed, onToggleCollapse, width, fill = false, dragOverId = null, onRename, onDelete }: Props = $props();
  let isDragging = $state(false);
  let laneEl = $state<HTMLDivElement | null>(null);
  let poppedOut = $state(false);

  function handleDragStart(e: DragEvent) {
    setLaneDrag(id);
    e.dataTransfer?.setData('text/x-lane-id', id);
    if (e.dataTransfer) e.dataTransfer.effectAllowed = 'move';
    isDragging = true;
  }

  function handleDragEnd() {
    isDragging = false;
    clearDrag();
  }

  const isDragOver = $derived(dragOverId === id);
</script>

{#if collapsed}
  <CollapsedLane laneId={id} title={title} onExpand={onToggleCollapse} draggable={true} onDragStart={handleDragStart} onDragEnd={handleDragEnd} {isDragging} />
{:else}
  <div
    role="group"
    aria-label={title}
    bind:this={laneEl}
    class={cn('lane', fill && 'lane--fill', isDragging && 'lane--dragging', isDragOver && !isDragging && 'lane--drag-over')}
    data-lane-id={id}
    style={fill ? 'width:100%;min-width:0;flex:1;' : `width:${width}rem;min-width:14rem;max-width:30rem;`}
  >
    <div class="stack-view">
      <LaneDragHandle
        title={title}
        {collapsed}
        onToggleCollapse={onToggleCollapse}
        onDragStart={handleDragStart}
        onDragEnd={handleDragEnd}
        {onRename}
        {onDelete}
        onPopout={() => (poppedOut = true)}
        poppedOut={poppedOut}
      />
      <div class="stack-content">
        {@render children?.()}
      </div>
    </div>
  </div>

  {#if poppedOut}
    <div class="lane-popout">
      <button type="button" class="lane-popout__backdrop" aria-label="Close lane popout" onclick={() => (poppedOut = false)}></button>
      <div class="lane-popout__panel">
        <div class="stack-view">
          <LaneDragHandle
            title={title}
            {collapsed}
            onToggleCollapse={onToggleCollapse}
            {onRename}
            {onDelete}
            onPopout={() => (poppedOut = false)}
            poppedOut={poppedOut}
          />
          <div class="lane-popout__body">
            {@render children?.()}
          </div>
        </div>
      </div>
    </div>
  {/if}
{/if}

// frontend/src/components/canvas/Lane.tsx
import * as React from 'react';
import { Resizer } from '~/components/resizer/Resizer';
import { CollapsedLane } from './CollapsedLane';
import { LaneDragHandle } from './LaneDragHandle';
import { setLaneDrag, clearDrag } from './dragState';
import { cn } from '~/utils/cn';

interface LaneProps {
  id: string;
  title: string;
  icon?: React.ReactNode;
  children: React.ReactNode;
  collapsed: boolean;
  onToggleCollapse: () => void;
  width: number; // rem
  showBorder?: boolean;
  minWidth?: number;
  maxWidth?: number;
  onWidthChange?: (w: number) => void;
  /** Lane ID currently being dragged over (from parent) */
  dragOverId?: string | null;
}

const LANE_RESIZER_CONFIG = {
  minWidth: 16,
  maxWidth: 40,
};

export const Lane: React.FC<LaneProps> = ({
  id,
  title,
  icon,
  children,
  collapsed,
  onToggleCollapse,
  width,
  showBorder = true,
  minWidth = LANE_RESIZER_CONFIG.minWidth,
  maxWidth = LANE_RESIZER_CONFIG.maxWidth,
  onWidthChange,
  dragOverId,
}) => {
  const laneRef = React.useRef<HTMLDivElement>(null);
  const [isDragging, setIsDragging] = React.useState(false);

  const handleDragStart = React.useCallback(
    (e: React.DragEvent) => {
      const target = e.target as HTMLElement;

      // If the drag originates from a draggable card, let the card handle it
      const cardEl = target.closest?.('[data-card-id]');
      if (cardEl) {
        return; // card's own dragstart will fire
      }

      // Only allow drag from the drag handle area
      const handle = target.closest?.('.lane-drag-handle');
      if (!handle) {
        e.preventDefault();
        return;
      }

      setLaneDrag(id);
      e.dataTransfer.setData('text/x-lane-id', id);
      e.dataTransfer.effectAllowed = 'move';
      setIsDragging(true);
    },
    [id],
  );

  const handleDragEnd = React.useCallback(() => {
    setIsDragging(false);
    clearDrag();
  }, []);

  if (collapsed) {
    return (
      <CollapsedLane
        id={id}
        title={title}
        icon={icon}
        onExpand={onToggleCollapse}
        draggable
        onDragStart={handleDragStart}
        onDragEnd={handleDragEnd}
        isDragging={isDragging}
      />
    );
  }

  const isDragOver = dragOverId === id;

  return (
    <div
      className={cn(
        'lane',
        isDragging && 'lane--dragging',
        isDragOver && !isDragging && 'lane--drag-over',
      )}
      data-lane-id={id}
      ref={laneRef}
      style={{ width: `${width}rem`, minWidth: `${minWidth}rem` }}
      draggable
      onDragStart={handleDragStart}
      onDragEnd={handleDragEnd}
    >
      <div className="stack-view">
        {/* Drag Handle */}
        <LaneDragHandle
          title={title}
          icon={icon}
          collapsed={collapsed}
          onToggleCollapse={onToggleCollapse}
        />

        {/* Lane Content: vertically stacked LaneCards */}
        <div className="stack-content">
          {children}
        </div>
      </div>

      {/* Right-side Resizer */}
      {laneRef.current && (
        <Resizer
          viewport={laneRef as React.RefObject<HTMLElement>}
          direction="right"
          minWidth={minWidth}
          maxWidth={maxWidth}
          defaultValue={width}
          showBorder={showBorder}
          syncName="lane-width"
          persistId={`lane-${id}-width`}
          onWidth={(w) => onWidthChange?.(w)}
        />
      )}
    </div>
  );
};
