// frontend/src/components/canvas/LaneCard.tsx
import * as React from 'react';
import { ChevronRight, X, GripVertical } from 'lucide-react';
import { setCardDrag, clearDrag } from './dragState';
import { cn } from '~/utils/cn';

interface LaneCardProps {
  id: string;
  header: React.ReactNode;
  children: React.ReactNode;
  defaultCollapsed?: boolean;
  persistId?: string;
  showBorder?: boolean;
  grow?: boolean;
  noshrink?: boolean;
  actions?: React.ReactNode;
  className?: string;
  /** Optional detail content shown in a side panel when expanded */
  detail?: React.ReactNode;
  /** Whether this card can be expanded to the side */
  expandable?: boolean;
  /** The lane ID this card belongs to (for cross-lane drag) */
  laneId?: string;
  /** Whether this card can be dragged to another lane */
  movable?: boolean;
}

function loadCollapsed(id: string): boolean {
  try {
    return localStorage.getItem(`xlchemy-card-${id}`) === 'true';
  } catch {
    return false;
  }
}

function saveCollapsed(id: string, v: boolean) {
  try {
    localStorage.setItem(`xlchemy-card-${id}`, String(v));
  } catch { /* ignore */ }
}

/**
 * Floating-style card with optional side-expansion and cross-lane dragging.
 * - PreviewHeader (42px) with chevron + title + actions
 * - Independently scrollable content
 * - When expanded, a detail panel drops down over the card content
 * - When movable, a grip handle allows dragging to another lane
 */
export const LaneCard: React.FC<LaneCardProps> = ({
  id,
  header,
  children,
  defaultCollapsed = false,
  showBorder = true,
  grow = false,
  noshrink = false,
  actions,
  className,
  detail,
  expandable = false,
  laneId,
  movable = false,
}) => {
  const [collapsed, setCollapsed] = React.useState(() => loadCollapsed(id) || defaultCollapsed);
  const [expanded, setExpanded] = React.useState(false);
  const [isDragging, setIsDragging] = React.useState(false);

  const handleToggle = React.useCallback(() => {
    setCollapsed((prev) => {
      const next = !prev;
      saveCollapsed(id, next);
      return next;
    });
  }, [id]);

  const handleExpandToggle = React.useCallback(() => {
    setExpanded((prev) => !prev);
  }, []);

  // Card drag for cross-lane movement
  const handleCardDragStart = React.useCallback(
    (e: React.DragEvent) => {
      if (!movable || !laneId) {
        e.preventDefault();
        return;
      }
      // Only allow drag from the grip area
      const grip = (e.target as HTMLElement).closest?.('.card-grip');
      if (!grip) {
        e.preventDefault();
        return;
      }
      e.stopPropagation(); // prevent lane's dragstart
      setCardDrag(id, laneId);
      e.dataTransfer.setData('text/x-card-id', id);
      e.dataTransfer.effectAllowed = 'move';
      setIsDragging(true);
    },
    [id, laneId, movable],
  );

  const handleCardDragEnd = React.useCallback(() => {
    setIsDragging(false);
    clearDrag();
  }, []);

  const showDetail = expandable && !!detail && expanded && !collapsed;

  return (
    <div
      className={cn(
        'drawer',
        grow && 'drawer--grow',
        noshrink && 'drawer--noshrink',
        collapsed && 'drawer--collapsed',
        showBorder && !collapsed && 'drawer--border',
        showDetail && 'drawer--expanded',
        isDragging && 'drawer--dragging',
        className,
      )}
      data-card-id={movable ? id : undefined}
      draggable={movable || undefined}
      onDragStart={movable ? handleCardDragStart : undefined}
      onDragEnd={movable ? handleCardDragEnd : undefined}
    >
      {/* PreviewHeader (42px, bg-2, border-bottom) */}
      <div className="drawer-header">
        <div className="drawer-header__title">
          <button
            type="button"
            className={cn('drawer-chevron', !collapsed && 'drawer-chevron--expanded')}
            onClick={handleToggle}
          >
            <ChevronRight className="w-3.5 h-3.5" />
          </button>
          <span className="drawer-header__text">{header}</span>
          {/* Card move grip (visible when movable) */}
          {movable && (
            <span className="card-grip" title="Drag to another lane">
              <GripVertical className="w-3 h-3.5" />
            </span>
          )}
        </div>
        {actions && (
          <div className="drawer-header__actions" onClick={(e) => e.stopPropagation()}>
            {actions}
          </div>
        )}
        {expandable && !collapsed && (
          <button
            type="button"
            className="drawer-chevron"
            onClick={handleExpandToggle}
            title={expanded ? 'Collapse detail' : 'Expand detail'}
            style={{
              marginLeft: 'auto',
              color: expanded ? 'var(--fill-pop-bg)' : undefined,
              transform: expanded ? 'rotate(90deg)' : 'rotate(-90deg)',
            }}
          >
            <ChevronRight className="w-3.5 h-3.5" />
          </button>
        )}
      </div>

      {/* Scrollable Content */}
      {!collapsed && (
        <div className="drawer-scroll">
          <div className="drawer__content">
            {children}
          </div>
        </div>
      )}

      {/* Side detail panel (absolute, drops down within card) */}
      {expandable && detail && showDetail && (
        <div className="drawer-detail">
          <button
            type="button"
            className="drawer-detail__close"
            onClick={() => setExpanded(false)}
            title="Close detail"
          >
            <X className="w-3.5 h-3.5" />
          </button>
          <div className="drawer-detail__inner">
            {detail}
          </div>
        </div>
      )}
    </div>
  );
};

// frontend/src/layout/LaneCard.svelte
<script lang="ts">
  import { cn } from '$lib/utils/cn';
  import { X, GripVertical, ChevronRight, Ellipsis } from '@lucide/svelte';
  import { clearDrag, setCardDrag } from '$lib/state/dragState';

  interface Props {
    id: string;
    header: string;
    children?: import('svelte').Snippet;
    defaultCollapsed?: boolean;
    showBorder?: boolean;
    grow?: boolean;
    noshrink?: boolean;
    actions?: import('svelte').Snippet;
    class?: string;
    detail?: import('svelte').Snippet;
    expandable?: boolean;
    laneId?: string;
    movable?: boolean;
  }

  let {
    id,
    header,
    children,
    defaultCollapsed = false,
    showBorder = true,
    grow = false,
    noshrink = false,
    actions,
    class: className = '',
    detail,
    expandable = false,
    laneId,
    movable = false,
  }: Props = $props();

  function loadCollapsed(id: string): boolean {
    try {
      return localStorage.getItem(`xlchemy-card-${id}`) === 'true';
    } catch {
      return false;
    }
  }

  function saveCollapsed(id: string, value: boolean) {
    try {
      localStorage.setItem(`xlchemy-card-${id}`, String(value));
    } catch {}
  }

  let collapsed = $state(false);
  let expanded = $state(false);
  let isDragging = $state(false);
  let didInit = false;

  $effect(() => {
    if (didInit) return;
    collapsed = loadCollapsed(id) || defaultCollapsed;
    didInit = true;
  });

  function handleToggle() {
    collapsed = !collapsed;
    saveCollapsed(id, collapsed);
  }

  function handleExpandToggle() {
    expanded = !expanded;
  }

  function handleCardDragStart(e: DragEvent) {
    if (!movable || !laneId) {
      e.preventDefault();
      return;
    }
    const target = e.target as HTMLElement;
    const grip = target.closest?.('.card-grip');
    if (!grip) {
      e.preventDefault();
      return;
    }
    e.stopPropagation();
    setCardDrag(id, laneId);
    e.dataTransfer?.setData('text/x-card-id', id);
    if (e.dataTransfer) e.dataTransfer.effectAllowed = 'move';
    isDragging = true;
  }

  function handleCardDragEnd() {
    isDragging = false;
    clearDrag();
  }

  const showDetail = $derived(expandable && !!detail && expanded && !collapsed);
</script>

<div
  role="group"
  aria-label={header}
  class={cn(
    'drawer',
    grow && 'drawer--grow',
    noshrink && 'drawer--noshrink',
    collapsed && 'drawer--collapsed',
    showBorder && !collapsed && 'drawer--border',
    showDetail && 'drawer--expanded',
    isDragging && 'drawer--dragging',
    className,
  )}
  data-card-id={movable ? id : undefined}
  draggable={movable}
  ondragstart={movable ? handleCardDragStart : undefined}
  ondragend={movable ? handleCardDragEnd : undefined}
>
  <div class="drawer-header">
    <div class="drawer-header__title">
      <button type="button" class={cn('drawer-chevron', !collapsed && 'drawer-chevron--expanded')} onclick={handleToggle}>
        <ChevronRight class="w-3.5 h-3.5" />
      </button>
      <span class="drawer-header__text">{header}</span>
      {#if movable}
        <span class="card-grip" title="Drag to another lane">
          <GripVertical class="w-3 h-3.5" />
        </span>
      {/if}
    </div>

    {#if actions}
      <div class="drawer-header__actions">{@render actions()}</div>
    {/if}

    <button type="button" class="lane-drag-handle__menu" title="More actions">
      <Ellipsis class="w-3.5 h-3.5" />
    </button>

    {#if expandable && !collapsed}
      <button
        type="button"
        class="drawer-chevron"
        onclick={handleExpandToggle}
        title={expanded ? 'Collapse detail' : 'Expand detail'}
        style={`margin-left:auto;color:${expanded ? 'var(--fill-pop-bg)' : 'inherit'};transform:${expanded ? 'rotate(90deg)' : 'rotate(-90deg)'}`}
      >
        <ChevronRight class="w-3.5 h-3.5" />
      </button>
    {/if}
  </div>

  {#if !collapsed}
    <div class="drawer-scroll">
      <div class="drawer__content">
        {@render children?.()}
      </div>
    </div>
  {/if}

  {#if detail && showDetail}
    <div class="drawer-detail">
      <button type="button" class="drawer-detail__close" onclick={() => (expanded = false)} title="Close detail">
        <X class="w-3.5 h-3.5" />
      </button>
      <div class="drawer-detail__inner">
        {@render detail()}
      </div>
    </div>
  {/if}
</div>
